import { getIcon, getImage } from "./imageloader";

export const Carddata = [
  {
    id: 1,
    icon: getIcon("red"),
    storeName: "너구리 직구상점",
    username: "@pumpkinraccoon",
    likes: 65,
    productCount: 3,
    label: "대표상품",
    products: [getImage("adidas1"), getImage("adidas2"), getImage("jacket")],
  },
  {
    id: 2,
    icon: getIcon("blue"),
    storeName: "구파발 보따리",
    username: "@hibottari",
    likes: 24,
    productCount: 2,
    label: "대표상품",
    products: [getImage("watch"), getImage("ring")],
  },
  {
    id: 3,
    icon: getIcon("red"),
    storeName: "COCO낸네",
    username: "@hibottari",
    likes: 38,
    productCount: 3,
    label: "대표상품",
    products: [getImage("towel"), getImage("cup"), getImage("bbyshoes")],
  },
  {
    id: 4,
    icon: getIcon("red"),
    storeName: "너구리 직구상점",
    username: "@pumpkinraccoon",
    likes: 65,
    productCount: 3,
    label: "대표상품",
    products: [getImage("adidas1"), getImage("adidas2"), getImage("jacket")],
  },
  {
    id: 5,
    icon: getIcon("blue"),
    storeName: "구파발 보따리",
    username: "@hibottari",
    likes: 24,
    productCount: 2,
    label: "대표상품",
    products: [getImage("watch"), getImage("ring")],
  },
  {
    id: 6,
    icon: getIcon("red"),
    storeName: "COCO낸네",
    username: "@hibottari",
    likes: 38,
    productCount: 3,
    label: "대표상품",
    products: [getImage("towel"), getImage("cup"), getImage("bbyshoes")],
  },
];
